version: "3"
services:
  carrige:
    build: .
    depends_on:
      - redis
      - postgres
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:latest"
    ports: 
      - "5432:5432"