version: "3"
name: iu
networks:
  iu:
services:
  carrige:
    build:
      dockerfile: Dockerfile
      context: "."
      args:
        GIT_PAT: ${GIT_PAT}
        GIT_USERNAME: ${GIT_USERNAME}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    entrypoint: "poetry run dev"
    volumes:
      - .:/app
    networks:
      - iu


  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    env_file:
      - .env
    networks:
      - iu

  s3_localstack:
    image: "localstack/localstack:s3-latest"
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - iu

