kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          imagePullPolicy: IfNotPresent
          image: redis:latest
          ports:
            - containerPort: 6379